// Bundles worker/src/index.js and shared/rules.js into one file, worker/dist/worker.js,
// that can be pasted straight into the Cloudflare dashboard editor.
// Run: node scripts/build-worker.mjs   (the deploy workflow checks it is up to date)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const strip = (file) => fs.readFileSync(path.join(root, file), 'utf8').replace(/^export (const|function|async function) /gm, '$1 ');
const rules = strip('shared/rules.js');
const tune = strip('shared/tune.js');
const worker = fs.readFileSync(path.join(root, 'worker/src/index.js'), 'utf8')
  .replace(/^import \{[^}]*\} from '\.\.\/\.\.\/shared\/(rules|tune)\.js';\n/gm, '');

const out = `// GENERATED by scripts/build-worker.mjs from worker/src/index.js and shared/rules.js.
// Paste this whole file into the Cloudflare Worker editor. Edit the sources, not this file.

// ===== shared/rules.js =====
${rules}
// ===== shared/tune.js =====
${tune}
// ===== worker/src/index.js =====
${worker}`;

const target = path.join(root, 'worker/dist/worker.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (current !== out) {
    console.error('worker/dist/worker.js is out of date. Run: node scripts/build-worker.mjs');
    process.exit(1);
  }
  console.log('worker/dist/worker.js is up to date.');
} else {
  fs.writeFileSync(target, out);
  console.log(`Wrote worker/dist/worker.js (${out.length} bytes).`);
}
